const Database = require('better-sqlite3');
const path = require('path');

// 本番環境では DB_PATH 環境変数で永続ディスクのパスを指定可能
const dbPath = process.env.DB_PATH || path.join(__dirname, 'forum.db');
const db = new Database(dbPath);

// WALモードで高速化
db.pragma('journal_mode = WAL');
db.pragma('foreign_keys = ON');

// テーブル作成（カテゴリなし、事件一覧をトップページに直接表示）
db.exec(`
  CREATE TABLE IF NOT EXISTS cases (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    year INTEGER,
    summary TEXT,
    tags TEXT,
    view_count INTEGER DEFAULT 0,
    post_count_cache INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
  );

  CREATE TABLE IF NOT EXISTS posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    case_id INTEGER NOT NULL,
    author_name TEXT NOT NULL DEFAULT '名無しの探偵',
    content TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (case_id) REFERENCES cases(id) ON DELETE CASCADE
  );

  CREATE INDEX IF NOT EXISTS idx_cases_year ON cases(year);
  CREATE INDEX IF NOT EXISTS idx_cases_updated ON cases(updated_at DESC);
  CREATE INDEX IF NOT EXISTS idx_cases_slug ON cases(slug);
  CREATE INDEX IF NOT EXISTS idx_posts_case ON posts(case_id);
`);

// 初期データ挿入
const caseCount = db.prepare('SELECT COUNT(*) as count FROM cases').get();
if (caseCount.count === 0) {
  const insertCase = db.prepare(
    'INSERT INTO cases (slug, title, year, summary, tags, view_count, post_count_cache, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)'
  );
  const insertPost = db.prepare(
    'INSERT INTO posts (case_id, author_name, content, created_at) VALUES (?, ?, ?, ?)'
  );

  const allCases = [
    {
      slug: 'osaka-video-arson',
      title: '大阪ビデオ店放火事件',
      year: 2008,
      summary: '大阪市浪速区の個室ビデオ店で放火が発生し、16人が死亡した大規模火災事件。犯人は店の客で、生活苦から自殺を図ろうとしたと供述。',
      tags: '放火,大阪,大量殺人',
      views: 820,
    },
    {
      slug: 'osaka-pachinko-arson',
      title: '大阪パチンコ店放火殺人事件',
      year: 2009,
      summary: '大阪市此花区のパチンコ店「クロスニコル」にガソリンがまかれ放火され、客ら5人が死亡した事件。',
      tags: '放火,大阪,大量殺人',
      views: 650,
    },
    {
      slug: 'inogashira',
      title: '井の頭公園バラバラ殺人事件',
      year: 1994,
      summary: '東京都三鷹市の井の頭公園でバラバラ遺体が発見された未解決事件。被害者の身元は判明したが犯人は不明のまま時効成立。',
      tags: '未解決,バラバラ殺人,東京',
      views: 1890,
    },
    {
      slug: 'iwate17',
      title: '岩手17歳女性殺害事件',
      year: 2008,
      summary: '岩手県洋野町で17歳の女性が殺害された事件。被害者の交友関係を中心に捜査が進められた。',
      tags: '殺人,岩手,少年犯罪',
      views: 430,
    },
    {
      slug: 'imaiti-stalker',
      title: '今市ストーカー殺人事件',
      year: 2013,
      summary: '栃木県日光市（旧今市市）でストーカー行為の末に女性が殺害された事件。DV・ストーカー対策の不備が問題視された。',
      tags: 'ストーカー,殺人,栃木',
      views: 510,
    },
    {
      slug: 'okegawa-stalker',
      title: '桶川ストーカー殺人事件',
      year: 1999,
      summary: 'JR桶川駅前で女子大生が元交際相手のグループに刺殺された事件。警察の怠慢な対応が社会問題となり、ストーカー規制法制定のきっかけとなった。',
      tags: 'ストーカー,殺人,埼玉,警察不祥事',
      views: 2150,
    },
    {
      slug: 'zushi-stalker',
      title: '逗子ストーカー殺人事件',
      year: 2012,
      summary: '神奈川県逗子市で元交際相手の男がDV防止法の保護命令中に女性を殺害した事件。役所の個人情報漏洩が問題となった。',
      tags: 'ストーカー,殺人,神奈川',
      views: 780,
    },
    {
      slug: 'nagasaki-stalker',
      title: '長崎ストーカー殺人事件',
      year: 2011,
      summary: '長崎県西海市で元交際相手の男が女性の母と祖母を殺害した事件。千葉県警と長崎県警の連携不足が問題視された。',
      tags: 'ストーカー,殺人,長崎,警察不祥事',
      views: 920,
    },
    {
      slug: 'kumagaya',
      title: '熊谷連続殺人事件',
      year: 2015,
      summary: '埼玉県熊谷市でペルー国籍の男が民家を次々と襲い、6人を殺害した連続殺人事件。精神鑑定が争点となった。',
      tags: '連続殺人,埼玉,家族殺害',
      views: 1340,
    },
    {
      slug: 'hirosima-taxi',
      title: '広島タクシー運転手殺害事件',
      year: 2000,
      summary: '広島県でタクシー運転手が乗客に殺害された強盗殺人事件。',
      tags: '殺人,強盗,広島',
      views: 320,
    },
    {
      slug: 'toyama-nagano',
      title: '富山・長野連続女性誘拐殺人事件',
      year: 2002,
      summary: '富山県と長野県で女性が相次いで誘拐・殺害された連続殺人事件。犯人は両事件で逮捕・死刑確定。',
      tags: '連続殺人,誘拐,殺人,富山,長野',
      views: 890,
    },
    {
      slug: 'yokohama-fukaya',
      title: '横浜・深谷連続殺人事件',
      year: 2001,
      summary: '横浜市と埼玉県深谷市で発生した連続殺人事件。金銭トラブルが動機とされる。',
      tags: '連続殺人,殺人,神奈川,埼玉',
      views: 420,
    },
    {
      slug: 'kurume-kangosi',
      title: '久留米看護師連続保険金殺人事件',
      year: 2003,
      summary: '福岡県久留米市の看護師が夫や知人に保険金をかけて殺害した連続保険金殺人事件。',
      tags: '保険金,連続殺人,福岡',
      views: 780,
    },
    {
      slug: 'kyoto-warabitori',
      title: '京都蕨取り殺人事件',
      year: 2004,
      summary: '京都府の山中でワラビ取りに来ていた女性が殺害された未解決事件。',
      tags: '未解決,殺人,京都',
      views: 560,
    },
    {
      slug: 'nagayama-jiken',
      title: '永山則夫連続射殺事件',
      year: 1968,
      summary: '永山則夫が東京・京都・函館・名古屋で4人を連続射殺した事件。死刑基準「永山基準」の由来となった歴史的事件。',
      tags: '連続殺人,殺人,歴史的事件',
      views: 2340,
    },
    {
      slug: 'hitachi-saisi6',
      title: '日立妻子6人殺害事件',
      year: 2017,
      summary: '茨城県日立市で男が妻と子供ら6人を殺害した家族殺害事件。',
      tags: '家族殺害,殺人,茨城',
      views: 670,
    },
    {
      slug: 'osaka-serialkiller',
      title: '大阪連続殺人事件',
      year: 2009,
      summary: '大阪で発生した連続殺人事件。複数の被害者が相次いで殺害された。',
      tags: '連続殺人,大阪',
      views: 580,
    },
    {
      slug: 'yamagata-tokyo',
      title: '山形・東京連続殺人事件',
      year: 2005,
      summary: '山形県と東京都にまたがる連続殺人事件。',
      tags: '連続殺人,山形,東京',
      views: 390,
    },
    {
      slug: 'himeji-2jyosei',
      title: '姫路2女性殺害事件',
      year: 2004,
      summary: '兵庫県姫路市で2人の女性が殺害された事件。',
      tags: '殺人,兵庫,未解決',
      views: 440,
    },
    {
      slug: 'barabara',
      title: '東京バラバラ殺人事件',
      year: 2006,
      summary: '東京で発生したバラバラ殺人事件。遺体が複数の場所で発見された。',
      tags: 'バラバラ殺人,東京',
      views: 720,
    },
    {
      slug: 'kakogawa7',
      title: '加古川7人殺害事件',
      year: 2004,
      summary: '兵庫県加古川市で発生した連続殺人事件。小学生女児刺殺事件を含む未解決事件。',
      tags: '未解決,殺人,兵庫',
      views: 950,
    },
    {
      slug: 'akita-jidou',
      title: '秋田児童連続殺害事件',
      year: 2006,
      summary: '秋田県藤里町で小学生2人が相次いで殺害された事件。犯人は近所に住む女で、自分の娘も殺害していたことが判明。',
      tags: '連続殺人,少年犯罪,秋田',
      views: 1670,
    },
    {
      slug: 'koutou-kamikakusi',
      title: '江東区神隠し殺人事件',
      year: 2008,
      summary: '東京都江東区のマンションで隣室の女性を拉致・殺害しバラバラにして遺棄した事件。防犯カメラの映像が決め手となった。',
      tags: 'バラバラ殺人,殺人,東京',
      views: 1230,
    },
    {
      slug: 'saitama-dog',
      title: '埼玉愛犬家連続殺人事件',
      year: 1993,
      summary: 'ブリーダーの男が犬の売買トラブルから複数人を殺害し、遺体を犬の餌に混ぜるなどして処理した猟奇的事件。',
      tags: '連続殺人,埼玉',
      views: 1450,
    },
    {
      slug: 'osaka-dog',
      title: '大阪愛犬家殺人事件',
      year: 2007,
      summary: '大阪で発生した愛犬家に関連する殺人事件。犬をめぐるトラブルが殺人に発展した。',
      tags: '殺人,大阪',
      views: 380,
    },
    {
      slug: 'mai-chan',
      title: '舞ちゃん殺害事件',
      year: 2003,
      summary: '幼い女児「舞ちゃん」が殺害された痛ましい事件。',
      tags: '殺人,少年犯罪',
      views: 560,
    },
    {
      slug: 'tottori-fusinsi',
      title: '鳥取連続不審死事件',
      year: 2009,
      summary: '鳥取県で男性6人が相次いで不審死した事件。上田美由紀被告がホステスとして接近し、睡眠薬で殺害したとされる。',
      tags: '連続殺人,毒殺,鳥取',
      views: 1380,
    },
    {
      slug: 'capitalarea-fusinsi',
      title: '首都圏連続不審死事件',
      year: 2009,
      summary: '木嶋佳苗が婚活サイトで知り合った男性3人を練炭自殺に見せかけて殺害した連続殺人事件。',
      tags: '連続殺人,毒殺,東京,埼玉',
      views: 1890,
    },
    {
      slug: 'niigata-kankin',
      title: '新潟少女監禁事件',
      year: 2000,
      summary: '新潟県柏崎市で9歳の少女が誘拐され、9年2か月にわたり監禁されていた事件。2000年に保護された際、大きな社会的衝撃を与えた。',
      tags: '誘拐,監禁,新潟',
      views: 2560,
    },
    {
      slug: 'nagoya-shufu',
      title: '名古屋主婦殺害事件',
      year: 2005,
      summary: '名古屋市で主婦が殺害された事件。',
      tags: '殺人,愛知',
      views: 340,
    },
    {
      slug: 'yuubari-hokenkin',
      title: '夕張保険金殺人事件',
      year: 1984,
      summary: '北海道夕張市で保険金目的の殺人が行われた事件。炭鉱の衰退した町で起きた保険金殺人。',
      tags: '保険金,殺人,北海道',
      views: 620,
    },
    {
      slug: 'nara-kidnap',
      title: '奈良小1女児殺害事件',
      year: 2004,
      summary: '奈良県奈良市で下校途中の小学1年生女児が誘拐・殺害された事件。犯人は新聞販売店員の男。',
      tags: '誘拐,殺人,少年犯罪,奈良',
      views: 1120,
    },
    {
      slug: 'takefuji-arson',
      title: '武富士弘前支店強盗殺人・放火事件',
      year: 2001,
      summary: '青森県弘前市の消費者金融「武富士」弘前支店に男が放火し、従業員5人が死亡した強盗殺人事件。',
      tags: '放火,強盗,殺人,青森',
      views: 890,
    },
    {
      slug: 'saga-wednesday',
      title: '佐賀水曜日事件',
      year: 2004,
      summary: '佐賀県で水曜日に連続して発生した事件。',
      tags: '殺人,佐賀',
      views: 310,
    },
    {
      slug: 'tojinbo-crime',
      title: '東尋坊突き落とし殺人事件',
      year: 2011,
      summary: '福井県の景勝地・東尋坊で男性が突き落とされて殺害された事件。保険金目的の犯行。',
      tags: '殺人,保険金,福井',
      views: 670,
    },
    {
      slug: 'matuyama-hostess',
      title: '松山ホステス殺害事件',
      year: 1982,
      summary: '愛媛県松山市でホステスが殺害された事件。福田和子が犯人として全国指名手配され、15年間の逃亡の末に逮捕。',
      tags: '殺人,逃亡,愛媛',
      views: 1340,
    },
    {
      slug: 'mabuchi-motor-crime',
      title: 'マブチモーター社長宅殺人放火事件',
      year: 2002,
      summary: 'マブチモーター社長宅に侵入した男が社長の妻と長女を殺害し放火した事件。犯人は他にも殺人を犯していた連続犯。',
      tags: '殺人,放火,強盗,千葉',
      views: 1120,
    },
    {
      slug: 'aconitum-crime',
      title: 'トリカブト保険金殺人事件',
      year: 1986,
      summary: '妻にトリカブトの毒を飲ませて殺害し保険金を詐取した事件。科学捜査が決め手となった。',
      tags: '毒殺,保険金,殺人',
      views: 1560,
    },
    {
      slug: 'gunma-stalker',
      title: '群馬ストーカー殺人事件',
      year: 2010,
      summary: '群馬県で発生したストーカー行為の末の殺人事件。',
      tags: 'ストーカー,殺人,群馬',
      views: 430,
    },
    {
      slug: 'hakamada-crime',
      title: '袴田事件',
      year: 1966,
      summary: '静岡県清水市で味噌製造会社の専務一家4人が殺害された事件。袴田巌が逮捕・死刑確定したが、2024年再審無罪。日本最大の冤罪事件の一つ。',
      tags: '冤罪,殺人,放火,静岡,歴史的事件',
      views: 3450,
    },
    {
      slug: 'nakatugawa',
      title: '中津川一家6人殺傷事件',
      year: 2005,
      summary: '岐阜県中津川市で男が妻の親族ら6人を殺傷した事件。',
      tags: '家族殺害,殺人,岐阜',
      views: 540,
    },
    {
      slug: 'beppu-3oku',
      title: '別府3億円保険金殺人事件',
      year: 1996,
      summary: '大分県別府市で保険金3億円を目的に殺人が行われた事件。',
      tags: '保険金,殺人,大分',
      views: 680,
    },
    {
      slug: 'takatiho6nin',
      title: '高千穂6人殺害事件',
      year: 2018,
      summary: '宮崎県高千穂町で男が家族や知人ら6人を殺害した後に自殺した事件。',
      tags: '家族殺害,殺人,宮崎',
      views: 890,
    },
    {
      slug: 'kamomae-yuki',
      title: '鴨前由紀殺害事件',
      year: 2005,
      summary: '女性が殺害された事件。事件の詳細な経緯が注目された。',
      tags: '殺人',
      views: 280,
    },
    {
      slug: 'tokusima-awaji',
      title: '徳島・淡路島事件',
      year: 2004,
      summary: '徳島県・淡路島にまたがる事件。',
      tags: '殺人,徳島,兵庫',
      views: 340,
    },
    {
      slug: 'kagosima-hioki5',
      title: '鹿児島日置5人殺害事件',
      year: 2018,
      summary: '鹿児島県日置市で5人が殺害された事件。',
      tags: '家族殺害,殺人,鹿児島',
      views: 560,
    },
    {
      slug: 'yamanakako-crime',
      title: '山中湖事件',
      year: 2007,
      summary: '山梨県山中湖村付近で発生した事件。',
      tags: '殺人,山梨',
      views: 310,
    },
    {
      slug: 'nisiguti-akira',
      title: '西口彰連続殺人事件',
      year: 1963,
      summary: '詐欺師の西口彰が逃亡中に次々と殺人を犯した連続殺人事件。佐木隆三の小説「復讐するは我にあり」のモデル。',
      tags: '連続殺人,歴史的事件',
      views: 1230,
    },
    {
      slug: 'kagawa-sakaide',
      title: '香川・坂出3人殺害事件',
      year: 2007,
      summary: '香川県坂出市で祖母と孫2人の3人が殺害された事件。近隣住民の男が逮捕された。',
      tags: '殺人,家族殺害,香川',
      views: 780,
    },
    {
      slug: 'simane-barabara',
      title: '島根女子大生バラバラ殺人事件',
      year: 2009,
      summary: '島根県立大学の女子大生が行方不明となり、バラバラ遺体で発見された事件。被疑者死亡のまま書類送検。',
      tags: 'バラバラ殺人,未解決,島根',
      views: 1670,
    },
    {
      slug: 'isinomaki',
      title: '石巻3人殺傷事件',
      year: 2010,
      summary: '宮城県石巻市で元交際相手の少年（18歳）が3人を殺傷した事件。少年に死刑判決が確定した稀有な事例。',
      tags: '殺人,少年犯罪,宮城',
      views: 1120,
    },
    {
      slug: 'hikarisi-bosi',
      title: '光市母子殺害事件',
      year: 1999,
      summary: '山口県光市で主婦と生後11か月の乳児が殺害された事件。少年法の適用や死刑制度について大きな議論を巻き起こした。',
      tags: '殺人,少年犯罪,山口',
      views: 2890,
    },
    {
      slug: 'fukuoka-bosi',
      title: '福岡母子殺害事件',
      year: 2003,
      summary: '福岡県で母子が殺害された事件。',
      tags: '殺人,福岡',
      views: 420,
    },
    {
      slug: 'nabari-poison-wine',
      title: '名張毒ぶどう酒事件',
      year: 1961,
      summary: '三重県名張市の公民館で毒入りぶどう酒により5人が死亡した事件。奥西勝が逮捕されたが、冤罪を主張しながら獄中で死亡。',
      tags: '毒殺,冤罪,三重,歴史的事件',
      views: 2230,
    },
    {
      slug: 'tutiura-tourima',
      title: '土浦連続殺傷事件',
      year: 2008,
      summary: '茨城県土浦市の荒川沖駅付近で男が通行人を次々と刺した通り魔事件。8人が殺傷された。',
      tags: '通り魔,殺人,茨城',
      views: 980,
    },
    {
      slug: 'ikedasyo-crime',
      title: '附属池田小事件',
      year: 2001,
      summary: '大阪教育大学附属池田小学校に男が侵入し、児童8人を殺害、教師を含む15人に重軽傷を負わせた事件。学校の安全対策が見直されるきっかけとなった。',
      tags: '通り魔,殺人,大阪,少年犯罪',
      views: 3120,
    },
    {
      slug: 'nagano-aichi',
      title: '長野・愛知連続殺人事件',
      year: 2006,
      summary: '長野県と愛知県で発生した連続殺人事件。',
      tags: '連続殺人,長野,愛知',
      views: 380,
    },
    {
      slug: 'isi-ikiume',
      title: '石井生き埋め事件',
      year: 2004,
      summary: '生き埋めにより殺害された事件。残忍な犯行手口が注目された。',
      tags: '殺人',
      views: 410,
    },
    {
      slug: 'jyosinsyo-crime',
      title: '上申書殺人事件',
      year: 2002,
      summary: '鳥取県で発覚した連続殺人事件。犯人が自ら上申書を提出したことから事件が発覚。',
      tags: '殺人,鳥取',
      views: 450,
    },
    {
      slug: 'poison-curry',
      title: '和歌山毒物カレー事件',
      year: 1998,
      summary: '和歌山県和歌山市の夏祭りでカレーにヒ素が混入され、4人が死亡・63人が急性ヒ素中毒になった事件。林眞須美に死刑判決。状況証拠のみの有罪認定に議論が続く。',
      tags: '毒殺,殺人,和歌山,冤罪',
      views: 4230,
    },
    {
      slug: 'kobe-kita5',
      title: '神戸市北区5人殺傷事件',
      year: 2014,
      summary: '神戸市北区で男が近隣住民ら5人を殺傷した事件。',
      tags: '殺人,兵庫',
      views: 540,
    },
    {
      slug: 'kouti-hokenkin',
      title: '高知保険金殺人事件',
      year: 2000,
      summary: '高知県で保険金を目的とした殺人事件が発生。',
      tags: '保険金,殺人,高知',
      views: 430,
    },
    {
      slug: 'yamanasi-camp-crime',
      title: '山梨キャンプ場女児失踪事件',
      year: 2019,
      summary: '山梨県道志村のキャンプ場で小学1年生の女児が行方不明となった事件。2022年に現場付近で遺骨の一部が発見されたが、全容は未解明。',
      tags: '失踪,未解決,山梨',
      views: 3890,
    },
    {
      slug: 'yamaguti-tukebi',
      title: '山口連続殺人放火事件',
      year: 2013,
      summary: '山口県周南市の限界集落で5人が殺害され、住宅に放火された事件。「つけび」の貼り紙が注目された。',
      tags: '連続殺人,放火,山口',
      views: 1780,
    },
    {
      slug: 'iwate-hirono',
      title: '岩手洋野町事件',
      year: 2006,
      summary: '岩手県洋野町で発生した事件。',
      tags: '殺人,岩手',
      views: 280,
    },
    {
      slug: 'nagasaki-saga',
      title: '長崎・佐賀連続保険金殺人事件',
      year: 2003,
      summary: '長崎県と佐賀県にまたがる保険金目的の連続殺人事件。',
      tags: '保険金,連続殺人,長崎,佐賀',
      views: 520,
    },
    {
      slug: 'miyazaki-2jyosei',
      title: '宮崎2女性殺害事件',
      year: 2007,
      summary: '宮崎県で2人の女性が殺害された事件。',
      tags: '殺人,宮崎',
      views: 340,
    },
    {
      slug: 'ibaraki-papakatu',
      title: '茨城パパ活殺人事件',
      year: 2021,
      summary: '茨城県で「パパ活」に関連して女性が殺害された事件。SNSを通じた出会いの危険性が問題提起された。',
      tags: '殺人,茨城',
      views: 980,
    },
    {
      slug: 'fukusima-exorcism',
      title: '福島悪魔祓い殺人事件',
      year: 1995,
      summary: '福島県須賀川市で宗教的儀式「悪魔祓い」の名目で女性が暴行され死亡した事件。',
      tags: '殺人,福島',
      views: 670,
    },
    {
      slug: 'osaka-sonezaki-arson',
      title: '大阪曽根崎ビル放火事件',
      year: 2021,
      summary: '大阪市北区曽根崎の心療内科クリニックで放火が発生し、院長ら26人が死亡した大惨事。犯人もその後死亡。',
      tags: '放火,大阪,大量殺人',
      views: 2340,
    },
    {
      slug: 'gunma-pachinko',
      title: '群馬パチンコ店強盗殺人事件',
      year: 2003,
      summary: '群馬県のパチンコ店で発生した強盗殺人事件。',
      tags: '強盗,殺人,群馬',
      views: 340,
    },
    {
      slug: 'akihabara-torima',
      title: '秋葉原無差別殺傷事件',
      year: 2008,
      summary: '東京都千代田区秋葉原の歩行者天国にトラックで突入後、通行人をナイフで次々と刺し7人が死亡、10人が負傷した事件。加藤智大に死刑執行。',
      tags: '通り魔,殺人,東京,大量殺人',
      views: 4560,
    },
    {
      slug: 'katuragi-jiken',
      title: '葛城事件',
      year: 2005,
      summary: '和歌山県で発生した事件。地域社会を揺るがした。',
      tags: '殺人,和歌山',
      views: 340,
    },
    {
      slug: 'tukuba-bosi',
      title: 'つくば母子殺害事件',
      year: 2010,
      summary: '茨城県つくば市で母子が殺害された事件。',
      tags: '殺人,茨城',
      views: 380,
    },
    {
      slug: 'nagano-3nin',
      title: '長野3人殺害事件',
      year: 2023,
      summary: '長野県中野市で男が猟銃と刃物で警察官2人と女性1人を殺害した立てこもり事件。',
      tags: '殺人,長野',
      views: 1450,
    },
    {
      slug: 'osaka-aiti-gifu',
      title: '大阪・愛知・岐阜連続リンチ殺人事件',
      year: 1994,
      summary: '大阪・愛知・岐阜にまたがり、少年グループが木曽川河川敷などで4人をリンチし殺害した凶悪事件。主犯格3人に死刑判決。',
      tags: 'リンチ,少年犯罪,連続殺人,大阪,愛知,岐阜',
      views: 1890,
    },
    {
      slug: 'kosei-jimujikan',
      title: '厚生事務次官連続殺傷事件',
      year: 2008,
      summary: '元厚生事務次官宅が相次いで襲撃され、2人が殺害された事件。犯人は「年金テロ」ではなくペット殺処分への恨みと供述。',
      tags: '連続殺人,殺人,東京,埼玉',
      views: 1230,
    },
    {
      slug: 'omuta-kitamura',
      title: '大牟田4人殺害事件',
      year: 2004,
      summary: '福岡県大牟田市で北村一家が知人一家4人を殺害した事件。家族4人全員に死刑判決。',
      tags: '殺人,家族殺害,福岡',
      views: 1340,
    },
    {
      slug: 'maiduru-kou1',
      title: '舞鶴高1女子殺害事件',
      year: 2008,
      summary: '京都府舞鶴市で高校1年生の女子生徒が殺害された未解決事件。被告人は無罪判決。',
      tags: '未解決,殺人,京都,冤罪',
      views: 890,
    },
    {
      slug: 'muroran-missing',
      title: '室蘭女子高生失踪事件',
      year: 2001,
      summary: '北海道室蘭市で女子高生が行方不明となった未解決事件。',
      tags: '失踪,未解決,北海道',
      views: 1120,
    },
    {
      slug: 'kumamoto-uto',
      title: '熊本宇土市殺人事件',
      year: 2011,
      summary: '熊本県宇土市で発生した殺人事件。',
      tags: '殺人,熊本',
      views: 280,
    },
    {
      slug: 'snack-mama',
      title: 'スナックママ殺害事件',
      year: 2005,
      summary: 'スナック経営の女性が殺害された事件。',
      tags: '殺人',
      views: 310,
    },
    {
      slug: 'okayama-barabara',
      title: '岡山バラバラ殺人事件',
      year: 2011,
      summary: '岡山県で発生したバラバラ殺人事件。',
      tags: 'バラバラ殺人,岡山',
      views: 450,
    },
    {
      slug: 'ginza-couple',
      title: '銀座カップル殺害事件',
      year: 2000,
      summary: '東京・銀座周辺でカップルが殺害された事件。',
      tags: '殺人,東京',
      views: 380,
    },
    {
      slug: 'sakai-gousatu',
      title: '堺市強殺事件',
      year: 2006,
      summary: '大阪府堺市で発生した強盗殺人事件。',
      tags: '強盗,殺人,大阪',
      views: 340,
    },
    {
      slug: 'yosikawa-yuri',
      title: '吉川友梨ちゃん失踪事件',
      year: 2003,
      summary: '大阪府熊取町で小学4年生の吉川友梨ちゃんが下校途中に行方不明となった未解決事件。',
      tags: '失踪,未解決,大阪',
      views: 1560,
    },
    {
      slug: 'kumatori-7nin',
      title: '熊取町7人連続怪死事件',
      year: 2003,
      summary: '大阪府泉南郡熊取町で住民7人が相次いで不審死した事件。自殺とされたが、不自然な共通点が指摘された。',
      tags: '未解決,不審死,大阪',
      views: 1230,
    },
    {
      slug: 'miyazaki-family3',
      title: '宮崎家族3人殺害事件',
      year: 2010,
      summary: '宮崎県で家族3人が殺害された事件。',
      tags: '家族殺害,殺人,宮崎',
      views: 380,
    },
    {
      slug: 'sapporo-parents',
      title: '札幌両親殺害事件',
      year: 2014,
      summary: '札幌市で両親が殺害された事件。',
      tags: '家族殺害,殺人,北海道',
      views: 340,
    },
    {
      slug: 'sinbasi-stalker',
      title: '新橋ストーカー殺人事件',
      year: 2013,
      summary: '東京都港区新橋で発生したストーカー行為の末の殺人事件。',
      tags: 'ストーカー,殺人,東京',
      views: 560,
    },
    {
      slug: 'nagoya-ninpu',
      title: '名古屋妊婦切り裂き殺人事件',
      year: 1988,
      summary: '名古屋市で妊婦が殺害され胎児を取り出された猟奇的未解決事件。犯人は不明のまま時効成立。',
      tags: '未解決,殺人,愛知',
      views: 1890,
    },
    {
      slug: 'fujibank-crime',
      title: '富士銀行行員顧客殺人事件',
      year: 1994,
      summary: '富士銀行（現みずほ銀行）の行員が顧客を殺害して金品を奪った事件。',
      tags: '殺人,強盗',
      views: 560,
    },
    {
      slug: 'sizuoka-2jyosei',
      title: '静岡2女性殺害事件',
      year: 2006,
      summary: '静岡県で2人の女性が殺害された事件。',
      tags: '殺人,静岡',
      views: 340,
    },
    {
      slug: 'ikebukuro-tourima',
      title: '池袋通り魔殺人事件',
      year: 1999,
      summary: '東京・池袋の繁華街で男が通行人を次々と刺し、2人が死亡、6人が負傷した通り魔事件。',
      tags: '通り魔,殺人,東京',
      views: 1450,
    },
    {
      slug: 'simonoseki-tourima',
      title: '下関通り魔殺人事件',
      year: 1999,
      summary: '山口県下関市のJR下関駅に車で突入し、さらに刃物で通行人を襲い5人が死亡した通り魔事件。',
      tags: '通り魔,殺人,山口',
      views: 1120,
    },
    {
      slug: 'matuda-tourima',
      title: '松田通り魔事件',
      year: 2003,
      summary: '通り魔による殺傷事件。',
      tags: '通り魔,殺人',
      views: 310,
    },
    {
      slug: 'tateyama-arson',
      title: '館山放火殺人事件',
      year: 2007,
      summary: '千葉県館山市で発生した放火殺人事件。',
      tags: '放火,殺人,千葉',
      views: 320,
    },
    {
      slug: 'maebasi-goutou',
      title: '前橋強盗殺人事件',
      year: 2008,
      summary: '群馬県前橋市で発生した強盗殺人事件。',
      tags: '強盗,殺人,群馬',
      views: 310,
    },
    {
      slug: 'ito-himono',
      title: '伊東市干物店女性殺害事件',
      year: 2004,
      summary: '静岡県伊東市の干物店で女性店主が殺害された未解決事件。',
      tags: '未解決,殺人,静岡',
      views: 450,
    },
    {
      slug: 'hatiouji-nanpei',
      title: '八王子スーパーナンペイ事件',
      year: 1995,
      summary: '東京都八王子市のスーパー「ナンペイ」で閉店作業中の女性従業員3人が拳銃で射殺された未解決事件。2015年に公訴時効が廃止されたため現在も捜査継続中。',
      tags: '未解決,殺人,強盗,東京',
      views: 3670,
    },
    {
      slug: 'hamanako-crime',
      title: '浜名湖切断遺体事件',
      year: 2009,
      summary: '静岡県の浜名湖で切断遺体が発見された事件。',
      tags: 'バラバラ殺人,静岡',
      views: 440,
    },
    {
      slug: 'neyagawa-student',
      title: '寝屋川中学生殺害事件',
      year: 2015,
      summary: '大阪府寝屋川市の中学生男女2人が殺害され、遺体が遺棄された事件。深夜の外出が問題視された。',
      tags: '殺人,少年犯罪,大阪',
      views: 1340,
    },
    {
      slug: 'nagoya-dark-site',
      title: '名古屋闇サイト殺人事件',
      year: 2007,
      summary: '闇サイトで知り合った3人の男が、帰宅途中の女性を拉致・殺害した事件。インターネットの闇が社会問題となった。',
      tags: '殺人,強盗,誘拐,愛知',
      views: 2120,
    },
    {
      slug: 'hekinan-gousatu',
      title: '碧南市強殺事件',
      year: 2004,
      summary: '愛知県碧南市で発生した強盗殺人事件。',
      tags: '強盗,殺人,愛知',
      views: 310,
    },
    {
      slug: 'osaka-drum',
      title: '大阪ドラム缶遺体事件',
      year: 2011,
      summary: '大阪でドラム缶の中から遺体が発見された事件。',
      tags: '殺人,大阪',
      views: 560,
    },
    {
      slug: 'kanie-bosi',
      title: '蟹江母子殺害事件',
      year: 2009,
      summary: '愛知県蟹江町で母子3人が殺傷された強盗殺人事件。遺留されたDNAから中国籍の男が逮捕された。',
      tags: '強盗,殺人,愛知',
      views: 780,
    },
    {
      slug: 'aizumisato-couple',
      title: '会津美里町夫婦殺害事件',
      year: 2013,
      summary: '福島県会津美里町で夫婦が殺害された事件。',
      tags: '殺人,福島',
      views: 310,
    },
    {
      slug: 'kaneiwa-barabara',
      title: '金沢・岩手バラバラ殺人事件',
      year: 2008,
      summary: '石川県金沢市と岩手県にまたがるバラバラ殺人事件。',
      tags: 'バラバラ殺人,石川,岩手',
      views: 450,
    },
    {
      slug: 'daigakusei-lynch',
      title: '大学生リンチ殺人事件',
      year: 2012,
      summary: '大学生がリンチにより殺害された事件。集団暴行の残虐さが社会に衝撃を与えた。',
      tags: 'リンチ,殺人',
      views: 560,
    },
    {
      slug: 'young-lynch',
      title: '少年リンチ殺人事件',
      year: 2000,
      summary: '少年グループによるリンチ殺人事件。少年法のあり方が議論された。',
      tags: 'リンチ,少年犯罪,殺人',
      views: 670,
    },
    {
      slug: 'fukuyama-gousatu',
      title: '福山市強殺事件',
      year: 2006,
      summary: '広島県福山市で発生した強盗殺人事件。',
      tags: '強盗,殺人,広島',
      views: 310,
    },
    {
      slug: 'filipino-2ladies',
      title: 'フィリピン人女性2人殺害事件',
      year: 2007,
      summary: 'フィリピン国籍の女性2人が殺害された事件。',
      tags: '殺人',
      views: 340,
    },
    {
      slug: 'colleague-wife',
      title: '同僚妻殺害事件',
      year: 2008,
      summary: '同僚の妻を殺害した事件。',
      tags: '殺人',
      views: 280,
    },
    {
      slug: 'oita-kaedama',
      title: '大分替え玉保険金殺人事件',
      year: 2005,
      summary: '大分県で替え玉を使った保険金詐取・殺人事件が発覚。',
      tags: '保険金,殺人,大分',
      views: 520,
    },
    {
      slug: 'fujima-seiha',
      title: '藤間静波連続殺人事件',
      year: 1992,
      summary: '藤間静波が3件の殺人を犯した連続殺人事件。死刑が確定し執行された。',
      tags: '連続殺人,殺人',
      views: 560,
    },
    {
      slug: 'nagoya-snack',
      title: '名古屋スナック殺人事件',
      year: 2007,
      summary: '名古屋市内のスナックで発生した殺人事件。',
      tags: '殺人,愛知',
      views: 310,
    },
    {
      slug: 'nerima-family',
      title: '練馬一家殺害事件',
      year: 2014,
      summary: '東京都練馬区で家族が殺害された事件。',
      tags: '家族殺害,殺人,東京',
      views: 450,
    },
    {
      slug: 'dd-house',
      title: 'DD殺人事件',
      year: 2012,
      summary: '不動産関連のトラブルから発展した殺人事件。',
      tags: '殺人',
      views: 340,
    },
    {
      slug: 'tomioka-hachimangu',
      title: '富岡八幡宮殺人事件',
      year: 2017,
      summary: '東京都江東区の富岡八幡宮の宮司が実弟に日本刀で殺害された事件。宮司職をめぐるお家騒動が背景。',
      tags: '殺人,東京',
      views: 1560,
    },
    {
      slug: 'ogura-misaki',
      title: '小倉美咲ちゃん失踪事件',
      year: 2019,
      summary: '山梨県道志村のキャンプ場で小学1年生の小倉美咲ちゃんが行方不明となった事件。（山梨キャンプ場女児失踪事件と同一）',
      tags: '失踪,未解決,山梨',
      views: 3200,
    },
    {
      slug: 'mizuuti-takasi',
      title: '水内貴士殺害事件',
      year: 2009,
      summary: '水内貴士さんが殺害された事件。',
      tags: '殺人',
      views: 280,
    },
    {
      slug: '4630',
      title: '阿武町4630万円誤送金事件',
      year: 2022,
      summary: '山口県阿武町が新型コロナ給付金4630万円を誤って1世帯に振り込み、受取人の男がオンラインカジノで使い込んだ事件。',
      tags: '詐欺,山口',
      views: 2890,
    },
    {
      slug: 'doberman',
      title: 'ドーベルマン逃走事件',
      year: 2021,
      summary: '千葉県でドーベルマンが逃走し住民が襲われた事件。飼い主の管理責任が問われた。',
      tags: '千葉',
      views: 560,
    },
    {
      slug: 'tomei-aori',
      title: '東名高速あおり運転事件',
      year: 2017,
      summary: '東名高速道路であおり運転により停車させられた夫婦が後続車に追突され死亡した事件。あおり運転厳罰化のきっかけとなった。',
      tags: '殺人,神奈川',
      views: 2340,
    },
    {
      slug: 'koganei-stalker',
      title: '小金井ストーカー殺人未遂事件',
      year: 2016,
      summary: '東京都小金井市で芸能活動をしていた女子大生がファンの男に刺された事件。SNSストーカーの危険性が浮き彫りに。',
      tags: 'ストーカー,殺人,東京',
      views: 1450,
    },
    {
      slug: 'abe-jyuugeki',
      title: '安倍晋三銃撃事件',
      year: 2022,
      summary: '奈良県奈良市で参院選の街頭演説中に安倍晋三元首相が銃撃され死亡した事件。犯人は旧統一教会への恨みを動機と供述。',
      tags: '殺人,奈良',
      views: 5670,
    },
    {
      slug: 'ichikawa-seki',
      title: '市川・関宿連続殺人事件',
      year: 2001,
      summary: '千葉県市川市と関宿町で発生した連続殺人事件。',
      tags: '連続殺人,千葉',
      views: 380,
    },
    {
      slug: 'nakamurabashi-police',
      title: '中村橋派出所襲撃事件',
      year: 1989,
      summary: '東京都練馬区の中村橋派出所が襲撃され警察官が殉職した事件。',
      tags: '殺人,東京',
      views: 560,
    },
    {
      slug: 'isehara-oyako',
      title: '伊勢原市親子殺害事件',
      year: 2010,
      summary: '神奈川県伊勢原市で親子が殺害された事件。',
      tags: '殺人,神奈川',
      views: 340,
    },
    {
      slug: 'kitami-sisanka',
      title: '北見市産婦人科殺人事件',
      year: 2003,
      summary: '北海道北見市の産婦人科で発生した殺人事件。',
      tags: '殺人,北海道',
      views: 380,
    },
    {
      slug: 'yokohama-barabara',
      title: '横浜バラバラ殺人事件',
      year: 2007,
      summary: '横浜市で発生したバラバラ殺人事件。',
      tags: 'バラバラ殺人,神奈川',
      views: 450,
    },
    {
      slug: 'sibamata-jyosidaisei',
      title: '柴又女子大生殺人事件',
      year: 1996,
      summary: '東京都葛飾区柴又で女子大生が自宅で殺害された未解決事件。犯人の侵入方法や動機は不明のまま。',
      tags: '未解決,殺人,東京',
      views: 1340,
    },
    {
      slug: 'matumoto-kenji',
      title: '松本健次殺害事件',
      year: 2004,
      summary: '松本健次さんが殺害された事件。',
      tags: '殺人',
      views: 280,
    },
    {
      slug: 'widearea118',
      title: '広域重要118号事件（グリコ・森永事件）',
      year: 1984,
      summary: '江崎グリコ社長誘拐に始まり、森永製菓など食品企業を脅迫した一連の企業恐喝事件。「かい人21面相」を名乗る犯人グループは未だ不明。日本犯罪史上最大の未解決事件。',
      tags: '未解決,誘拐,脅迫,大阪,歴史的事件',
      views: 4890,
    },
    {
      slug: 'nakamaware',
      title: '中間市殺人事件',
      year: 2004,
      summary: '福岡県中間市で発生した殺人事件。',
      tags: '殺人,福岡',
      views: 280,
    },
    {
      slug: 'totigi-cho',
      title: '栃木小1女児殺害事件',
      year: 2005,
      summary: '栃木県今市市（現日光市）で小学1年生の女児が下校途中に誘拐・殺害された事件。',
      tags: '誘拐,殺人,少年犯罪,栃木',
      views: 1120,
    },
    {
      slug: 'utunomiya-brother',
      title: '宇都宮兄弟殺害事件',
      year: 2008,
      summary: '栃木県宇都宮市で兄弟が殺害された事件。',
      tags: '殺人,栃木',
      views: 340,
    },
    {
      slug: 'sakai-eto',
      title: '堺市江藤殺害事件',
      year: 2009,
      summary: '大阪府堺市で江藤さんが殺害された事件。',
      tags: '殺人,大阪',
      views: 310,
    },
    {
      slug: 'maebasi-snack',
      title: '前橋スナック殺人事件',
      year: 2003,
      summary: '群馬県前橋市のスナックで発生した殺人事件。',
      tags: '殺人,群馬',
      views: 310,
    },
    {
      slug: 'myougi-sanroku',
      title: '妙義山麓殺人事件',
      year: 2007,
      summary: '群馬県の妙義山麓で遺体が発見された殺人事件。',
      tags: '殺人,群馬',
      views: 340,
    },
    {
      slug: 'nagoya-maria',
      title: '名古屋マリア殺人事件',
      year: 2005,
      summary: '名古屋市で発生した殺人事件。',
      tags: '殺人,愛知',
      views: 310,
    },
    {
      slug: 'kawasaki-tourima',
      title: '川崎通り魔事件',
      year: 2019,
      summary: '川崎市多摩区の登戸駅付近でスクールバスを待つ児童らが刺され、2人が死亡・18人が負傷した通り魔事件。犯人はその場で自殺。',
      tags: '通り魔,殺人,神奈川',
      views: 2560,
    },
    {
      slug: 'matudo-lin',
      title: '松戸女児殺害事件（リンちゃん事件）',
      year: 2017,
      summary: '千葉県松戸市でベトナム国籍の小学3年生レェ・ティ・ニャット・リンちゃんが保護者会会長の男に殺害された事件。',
      tags: '殺人,少年犯罪,千葉',
      views: 1450,
    },
    {
      slug: 'touden-ol',
      title: '東電OL殺人事件',
      year: 1997,
      summary: '東京電力の女性社員が殺害された事件。ネパール人男性が逮捕・有罪となったが、2012年にDNA鑑定で再審無罪。冤罪事件。',
      tags: '殺人,冤罪,東京',
      views: 2340,
    },
    {
      slug: 'piano-noise',
      title: 'ピアノ騒音殺人事件',
      year: 1974,
      summary: '神奈川県平塚市でピアノの騒音を理由に隣人が母子3人を殺害した事件。騒音問題の深刻さを世に知らしめた。',
      tags: '殺人,家族殺害,神奈川,歴史的事件',
      views: 1120,
    },
    {
      slug: 'osaka-sister',
      title: '大阪姉妹殺害事件',
      year: 2005,
      summary: '大阪市浪速区のマンションで姉妹が殺害された事件。前科のある男が犯人で、出所後の監視体制の不備が問題視された。',
      tags: '殺人,大阪',
      views: 890,
    },
    {
      slug: 'handsome-murderer',
      title: 'イケメン殺人事件',
      year: 2009,
      summary: '容姿端麗な犯人による殺人事件として注目された。',
      tags: '殺人',
      views: 450,
    },
    {
      slug: 'totigi-lynch',
      title: '栃木リンチ殺人事件',
      year: 1999,
      summary: '栃木県で少年らが19歳の男性を長期間にわたりリンチし殺害した事件。被害者の両親が警察の不作為を訴えた。',
      tags: 'リンチ,少年犯罪,殺人,栃木,警察不祥事',
      views: 1560,
    },
    {
      slug: 'yamato-shufu',
      title: '大和市主婦殺害事件',
      year: 2005,
      summary: '神奈川県大和市で主婦が殺害された事件。',
      tags: '殺人,神奈川',
      views: 310,
    },
    {
      slug: 'tama-pachinko',
      title: '多摩パチンコ店強盗事件',
      year: 2007,
      summary: '東京都多摩地区のパチンコ店で発生した強盗事件。',
      tags: '強盗,東京',
      views: 310,
    },
    {
      slug: 'matumura-kyozo',
      title: '松村恭造殺害事件',
      year: 2010,
      summary: '松村恭造さんが殺害された事件。',
      tags: '殺人',
      views: 280,
    },
    {
      slug: 'jt-sakaurami',
      title: 'JT女性社員逆恨み殺人事件',
      year: 2009,
      summary: 'JT社員の女性が元交際相手の逆恨みにより殺害された事件。',
      tags: 'ストーカー,殺人',
      views: 560,
    },
    {
      slug: 'kumamoto-kidnap',
      title: '熊本女児誘拐殺害事件',
      year: 2011,
      summary: '熊本県で女児が誘拐・殺害された事件。',
      tags: '誘拐,殺人,熊本',
      views: 560,
    },
    {
      slug: 'fukuoka-3jyosei',
      title: '福岡3女性殺害事件',
      year: 2003,
      summary: '福岡県で3人の女性が相次いで殺害された連続殺人事件。',
      tags: '連続殺人,殺人,福岡',
      views: 670,
    },
    {
      slug: 'mie-shot-dead',
      title: '三重県射殺事件',
      year: 2006,
      summary: '三重県で発生した銃による殺人事件。',
      tags: '殺人,三重',
      views: 340,
    },
    {
      slug: 'hirosima-hokenkin',
      title: '広島保険金殺人事件',
      year: 1998,
      summary: '広島県で保険金目的の殺人事件が発生。',
      tags: '保険金,殺人,広島',
      views: 450,
    },
    {
      slug: 'killing-classmate',
      title: '同級生殺害事件',
      year: 2004,
      summary: '同級生を殺害した事件。学校内での人間関係トラブルが原因。',
      tags: '殺人,少年犯罪',
      views: 560,
    },
    {
      slug: 'manila-crime',
      title: 'マニラ保険金殺人事件',
      year: 1999,
      summary: 'フィリピン・マニラで日本人が保険金目的で殺害された事件。',
      tags: '保険金,殺人,海外',
      views: 450,
    },
    {
      slug: 'sinagawa-seimenjyo',
      title: '品川製麺所殺人事件',
      year: 2007,
      summary: '東京都品川区の製麺所で発生した殺人事件。',
      tags: '殺人,東京',
      views: 310,
    },
    {
      slug: 'himeji-pachinko',
      title: '姫路パチンコ店殺人事件',
      year: 2005,
      summary: '兵庫県姫路市のパチンコ店で発生した殺人事件。',
      tags: '殺人,兵庫',
      views: 310,
    },
    {
      slug: 'kawasaki-tenraku',
      title: '川崎転落殺人事件',
      year: 2015,
      summary: '川崎市で少年が河川敷から突き落とされて死亡した事件。（川崎市中1男子生徒殺害事件）少年グループによる犯行。',
      tags: '殺人,少年犯罪,神奈川',
      views: 1780,
    },
    {
      slug: 'fujisima-mituo',
      title: '藤島光雄事件',
      year: 2001,
      summary: '藤島光雄による殺人事件。',
      tags: '殺人',
      views: 280,
    },
    {
      slug: 'manila-hokenkin',
      title: 'マニラ保険金詐欺殺人事件',
      year: 2005,
      summary: 'マニラで保険金をかけて殺害する計画が実行された事件。',
      tags: '保険金,殺人,海外',
      views: 450,
    },
    {
      slug: 'miharu-hikinige',
      title: '三春ひき逃げ事件',
      year: 2008,
      summary: '福島県三春町で発生したひき逃げ事件。',
      tags: '福島',
      views: 280,
    },
    {
      slug: 'cosmo-research',
      title: 'コスモリサーチ事件',
      year: 2005,
      summary: '調査会社コスモリサーチに関連する殺人事件。',
      tags: '殺人',
      views: 340,
    },
    {
      slug: 'nagoya-oldcouple',
      title: '名古屋老夫婦殺害事件',
      year: 2009,
      summary: '名古屋市で老夫婦が殺害された事件。',
      tags: '殺人,愛知',
      views: 380,
    },
    {
      slug: 'mie-filipino',
      title: '三重フィリピン人殺害事件',
      year: 2006,
      summary: '三重県でフィリピン人が殺害された事件。',
      tags: '殺人,三重',
      views: 310,
    },
    {
      slug: 'sm-club-crime',
      title: 'SMクラブ殺人事件',
      year: 1997,
      summary: 'SMクラブに関連する殺人事件。',
      tags: '殺人',
      views: 380,
    },
    {
      slug: 'kofu-sinkin-ol',
      title: '甲府信金OL殺害事件',
      year: 2002,
      summary: '山梨県甲府市の信用金庫の女性職員が殺害された未解決事件。',
      tags: '未解決,殺人,山梨',
      views: 670,
    },
    {
      slug: 'hatukaiti-jyosikousei',
      title: '廿日市女子高生殺害事件',
      year: 2004,
      summary: '広島県廿日市市で女子高生が自宅で殺害された事件。14年後の2018年にDNA型鑑定で犯人が逮捕された。',
      tags: '殺人,広島',
      views: 1120,
    },
    {
      slug: 'katuta-kiyotaka',
      title: '勝田清孝連続殺人事件',
      year: 1972,
      summary: '消防士の勝田清孝が1972年から1983年にかけて8人を殺害した連続殺人事件。二重生活を送っていた。',
      tags: '連続殺人,歴史的事件',
      views: 1120,
    },
    {
      slug: 'kurebayasi',
      title: '榎林事件',
      year: 2003,
      summary: '殺人事件。事件の詳細が注目された。',
      tags: '殺人',
      views: 280,
    },
    {
      slug: 'sinkansen',
      title: '新幹線殺傷事件',
      year: 2018,
      summary: '東海道新幹線の車内で男が乗客を刃物で襲い、1人が死亡・2人が重傷を負った事件。密閉空間での犯行に衝撃が走った。',
      tags: '通り魔,殺人,神奈川',
      views: 1890,
    },
    {
      slug: 'tuyama-s3',
      title: '津山事件（津山三十人殺し）',
      year: 1938,
      summary: '岡山県津山市の山村で都井睦雄が一夜にして30人を殺害した日本犯罪史上最悪の大量殺人事件。横溝正史「八つ墓村」のモデル。',
      tags: '大量殺人,殺人,岡山,歴史的事件',
      views: 3560,
    },
    {
      slug: 'sinsaibasi-torima',
      title: '心斎橋通り魔事件',
      year: 2012,
      summary: '大阪市中央区心斎橋の路上で男が通行人を刺し、2人が死亡した通り魔事件。',
      tags: '通り魔,殺人,大阪',
      views: 890,
    },
    {
      slug: 'nisitetu-bus',
      title: '西鉄バスジャック事件',
      year: 2000,
      summary: '17歳の少年が佐賀発福岡行きの高速バスをハイジャックし、1人が死亡した事件。少年犯罪とネット社会の問題が浮上。',
      tags: '少年犯罪,殺人,福岡,佐賀',
      views: 1670,
    },
    {
      slug: 'honjyo-hokenkin',
      title: '本庄保険金殺人事件',
      year: 1995,
      summary: '埼玉県本庄市で保険金目的の連続殺人。八木茂が愛人らと共謀し、知人らに保険金をかけて毒殺。',
      tags: '保険金,毒殺,連続殺人,埼玉',
      views: 1120,
    },
    {
      slug: 'ibaraki-lynch',
      title: '茨城リンチ殺人事件',
      year: 2009,
      summary: '茨城県で発生したリンチによる殺人事件。',
      tags: 'リンチ,殺人,茨城',
      views: 450,
    },
    {
      slug: 'oguti-hospital',
      title: '大口病院連続点滴中毒死事件',
      year: 2016,
      summary: '横浜市の旧大口病院で看護師が点滴に消毒液を混入し、入院患者を殺害した連続殺人事件。',
      tags: '連続殺人,毒殺,神奈川',
      views: 1560,
    },
    {
      slug: 'nagano-tatekomori',
      title: '長野立てこもり発砲事件',
      year: 2023,
      summary: '長野県中野市で猟銃と刃物を使い4人を殺害し、自宅に立てこもった事件。',
      tags: '殺人,長野',
      views: 1340,
    },
    {
      slug: 'funabasi-lynch',
      title: '船橋リンチ殺人事件',
      year: 2001,
      summary: '千葉県船橋市で発生したリンチによる殺人事件。',
      tags: 'リンチ,殺人,千葉',
      views: 450,
    },
    {
      slug: 'niigata-girl',
      title: '新潟女児殺害事件',
      year: 2018,
      summary: '新潟県新潟市で小学2年生の女児が殺害され線路上に遺棄された事件。近隣に住む男が逮捕。',
      tags: '殺人,少年犯罪,新潟',
      views: 1340,
    },
    {
      slug: 'kasukabe-chinese',
      title: '春日部中国人殺害事件',
      year: 2005,
      summary: '埼玉県春日部市で中国人が殺害された事件。',
      tags: '殺人,埼玉',
      views: 310,
    },
    {
      slug: 'miyazaki-tutomu',
      title: '宮崎勤連続幼女誘拐殺人事件',
      year: 1988,
      summary: '東京都と埼玉県で4人の幼女が誘拐・殺害された連続殺人事件。犯人の宮崎勤の自室から大量のビデオテープが発見され、オタクバッシングが社会問題化。',
      tags: '連続殺人,誘拐,少年犯罪,東京,埼玉,歴史的事件',
      views: 3890,
    },
    {
      slug: 'kasiwa-tourima',
      title: '柏通り魔事件',
      year: 2014,
      summary: '千葉県柏市で通行人が次々と刺された通り魔事件。',
      tags: '通り魔,殺人,千葉',
      views: 670,
    },
    {
      slug: 'nagoya-hirahirasan',
      title: '名古屋ひらひらさん事件',
      year: 2007,
      summary: '名古屋市で発生した事件。ネット上での呼称「ひらひらさん」で知られる。',
      tags: '殺人,愛知',
      views: 340,
    },
    {
      slug: 'sasebo-jyosikousei',
      title: '佐世保女子高生殺害事件',
      year: 2014,
      summary: '長崎県佐世保市で高校1年生の女子生徒が同級生を殺害し遺体を解体した事件。少女の異常な行動歴が明らかに。',
      tags: '殺人,少年犯罪,バラバラ殺人,長崎',
      views: 2120,
    },
    {
      slug: 'kyoani-houka',
      title: '京都アニメーション放火殺人事件',
      year: 2019,
      summary: '京都市伏見区の京都アニメーション第1スタジオにガソリンがまかれ放火され、36人が死亡した事件。戦後最悪の放火殺人。',
      tags: '放火,大量殺人,京都',
      views: 4890,
    },
    {
      slug: 'fukuoka-akahori-hokenkin',
      title: '福岡赤堀保険金殺人事件',
      year: 2005,
      summary: '福岡県で保険金目的の殺人事件が発生。',
      tags: '保険金,殺人,福岡',
      views: 380,
    },
    {
      slug: 'awajisima-5nin',
      title: '淡路島5人殺害事件',
      year: 2015,
      summary: '兵庫県淡路島で近隣住民5人が殺害された事件。犯人は精神疾患を抱えていた。',
      tags: '殺人,家族殺害,兵庫',
      views: 1120,
    },
    {
      slug: 'thrift-shop-crime',
      title: 'リサイクルショップ殺人事件',
      year: 2007,
      summary: 'リサイクルショップで発生した殺人事件。',
      tags: '殺人',
      views: 310,
    },
    {
      slug: 'ichihasi-tatuya',
      title: '市橋達也事件（英国人女性殺害事件）',
      year: 2007,
      summary: '千葉県市川市で英国人英会話講師リンゼイ・アン・ホーカーさんが殺害された事件。犯人の市橋達也は整形手術を経て2年7か月逃亡。',
      tags: '殺人,逃亡,千葉',
      views: 2560,
    },
    {
      slug: 'hannou-family',
      title: '飯能夫婦殺害事件',
      year: 2013,
      summary: '埼玉県飯能市で夫婦が殺害された事件。',
      tags: '殺人,埼玉',
      views: 340,
    },
    {
      slug: 'sasebo-nebada',
      title: '佐世保小6女児同級生殺害事件（ネバダ事件）',
      year: 2004,
      summary: '長崎県佐世保市の小学校で6年生の女児が同級生にカッターナイフで殺害された事件。加害者が11歳だったことに衝撃。',
      tags: '殺人,少年犯罪,長崎',
      views: 2340,
    },
    {
      slug: 'ibaraki-family',
      title: '茨城一家殺傷事件',
      year: 2019,
      summary: '茨城県境町で一家4人が殺傷された事件。2021年にフィリピン国籍の男が逮捕。',
      tags: '殺人,家族殺害,茨城',
      views: 1120,
    },
    {
      slug: 'yamamoto-miyuki',
      title: '山本美幸事件',
      year: 2012,
      summary: '保険金目的の殺人事件。山本美幸が関与。',
      tags: '保険金,殺人',
      views: 380,
    },
    {
      slug: 'fukuoka-snack-mama',
      title: '福岡スナックママ殺害事件',
      year: 2006,
      summary: '福岡県でスナック経営の女性が殺害された事件。',
      tags: '殺人,福岡',
      views: 310,
    },
    {
      slug: 'toyokawa-family5',
      title: '豊川家族5人殺害事件',
      year: 1999,
      summary: '愛知県豊川市で17歳の少年が隣家の5人を殺害した事件。',
      tags: '殺人,少年犯罪,家族殺害,愛知',
      views: 890,
    },
    {
      slug: 'syodosima-parents',
      title: '小豆島両親殺害事件',
      year: 2007,
      summary: '香川県小豆島で両親が殺害された事件。',
      tags: '家族殺害,殺人,香川',
      views: 340,
    },
    {
      slug: 'sakai-rentan',
      title: '堺市練炭殺人事件',
      year: 2009,
      summary: '大阪府堺市で練炭を使った殺人事件。',
      tags: '殺人,大阪',
      views: 380,
    },
    {
      slug: 'yamato-incident',
      title: '大和事件',
      year: 2006,
      summary: '神奈川県大和市で発生した事件。',
      tags: '殺人,神奈川',
      views: 280,
    },
    {
      slug: 'akiruno-sisanka',
      title: 'あきる野市死産児事件',
      year: 2010,
      summary: '東京都あきる野市で発生した事件。',
      tags: '東京',
      views: 280,
    },
    {
      slug: 'misima-tandaisei',
      title: '三島短大生殺害事件',
      year: 2002,
      summary: '静岡県三島市で短大生が殺害された事件。',
      tags: '殺人,静岡',
      views: 380,
    },
    {
      slug: 'numadu-stalker',
      title: '沼津ストーカー殺人事件',
      year: 2012,
      summary: '静岡県沼津市で発生したストーカー行為の末の殺人事件。',
      tags: 'ストーカー,殺人,静岡',
      views: 450,
    },
    {
      slug: 'koufu-houkasatujin',
      title: '甲府放火殺人事件',
      year: 2021,
      summary: '山梨県甲府市で19歳の少年が交際相手の両親を殺害し住宅に放火した事件。',
      tags: '放火,殺人,少年犯罪,山梨',
      views: 1120,
    },
    {
      slug: 'totigi-syo1girl',
      title: '栃木小1女児殺害事件',
      year: 2005,
      summary: '栃木県今市市で小学1年生の女児が下校途中に行方不明となり、翌日に遺体が発見された事件。',
      tags: '殺人,少年犯罪,栃木',
      views: 1120,
    },
    {
      slug: '121crime',
      title: '1億2100万円強盗事件',
      year: 2004,
      summary: '大規模な強盗事件。被害額の大きさが注目された。',
      tags: '強盗',
      views: 450,
    },
    {
      slug: 'father-crime',
      title: '尊属殺人事件（父殺し事件）',
      year: 1968,
      summary: '実父を殺害した娘に対する裁判で、尊属殺人罪の重罰規定が違憲とされた歴史的判決。1973年最高裁で違憲判決。',
      tags: '殺人,冤罪,歴史的事件',
      views: 1670,
    },
  ];

  // 有名事件へのサンプル投稿データ
  const samplePosts = {
    // 世田谷 = widearea118ではなく、世田谷は別途追加が必要 → 八王子ナンペイ事件にある
    // 和歌山カレー = poison-curry
    // グリコ森永 = widearea118
    // 八王子ナンペイ = hatiouji-nanpei
    // 秋葉原通り魔 = akihabara-torima
    'poison-curry': [
      {
        author: '名無しの法学生',
        content: '状況証拠のみで死刑判決というのは、やはり重い問題だと思います。ヒ素の鑑定についても、近年の再検証では同一性に疑問が呈されています。科学鑑定の再検証は必要ではないでしょうか。',
        date: '2026-03-18 11:30:00',
      },
      {
        author: '地元住民',
        content: '当時の報道を覚えていますが、メディアの印象操作も相当あったように思います。自宅前にカメラが並び、まるで犯人と決めつけたかのような報道でした。冷静な再検証を望みます。',
        date: '2026-03-19 07:45:00',
      },
      {
        author: '化学に詳しい人',
        content: 'SPring-8でのヒ素鑑定は当時画期的とされましたが、最近の論文では分析精度に限界があるとの指摘もあります。同じ鉱山由来のヒ素なら類似のパターンを示す可能性は否定できません。',
        date: '2026-03-20 14:20:00',
      },
    ],
    'widearea118': [
      {
        author: '昭和事件研究会',
        content: 'グリコ・森永事件の犯行声明文の文体分析から、かなり教養のある人物だったことは間違いないと思います。関西弁を使いつつも文章構成は洗練されていました。「かい人21面相」という名前のセンスも独特です。',
        date: '2026-03-23 00:15:00',
      },
      {
        author: '犯罪心理に興味',
        content: '企業を相手にした脅迫でありながら、最終的に金銭を受け取ることに失敗しているのが不思議です。本当に金が目的だったのか、それとも別の動機があったのか。社会への怒りや復讐のようなものを感じます。',
        date: '2026-03-24 18:30:00',
      },
      {
        author: '名無しの探偵',
        content: 'キツネ目の男の似顔絵は日本中に配布されましたが、結局特定には至りませんでした。複数犯説が有力ですが、組織の規模と構成は未だに謎。2000年に時効が成立してしまったのが悔やまれます。',
        date: '2026-03-25 09:00:00',
      },
    ],
    'hatiouji-nanpei': [
      {
        author: '多摩の住民',
        content: '1995年に発生してからもう30年以上。3人の女性が射殺されるという凄惨な事件でした。2007年に時効が廃止されたため、今も捜査は継続中のはずですが、進展はあるのでしょうか。',
        date: '2026-03-20 14:00:00',
      },
      {
        author: '銃器マニア',
        content: '犯行に使われた銃は中国製の拳銃「トカレフ」だったという情報がありますね。当時の銃の流通ルートから犯人像を絞れないものでしょうか。暴力団関係者の線も捨てきれません。',
        date: '2026-03-20 16:30:00',
      },
    ],
    'akihabara-torima': [
      {
        author: '事件研究家',
        content: '加藤智大は犯行前にネット掲示板に大量の書き込みをしていました。派遣切りへの不満、社会への怒り、孤独感...。あの書き込みの段階で誰かが気づいて介入できていたら、と思わずにはいられません。',
        date: '2026-03-25 10:30:00',
      },
      {
        author: '名無しの社会学者',
        content: 'この事件をきっかけに歩行者天国は長期間中止されました。社会が変わった事件の一つです。非正規雇用の問題、ネット上の孤独、社会からの疎外感...構造的な問題が凝縮されていた事件だと思います。',
        date: '2026-03-26 08:45:00',
      },
      {
        author: '秋葉原の住民',
        content: '当日あの場にいた友人がいます。トラックが突っ込んできた時の恐怖は今でも忘れられないと言っていました。現場に献花に行くたびに、二度とこんな事件が起きないことを祈ります。',
        date: '2026-03-27 12:00:00',
      },
    ],
  };

  // 世田谷一家殺害事件を追加（URLスラッグリストにはないが、有名事件のためサンプル投稿用に追加）
  // 注意: slugリストにないので、代わりにkobe-kita5の後に追加
  // → 実際にはURLリストにないが、サンプル投稿があるので別途追加する
  const setagayaCase = {
    slug: 'setagaya-family',
    title: '世田谷一家殺害事件',
    year: 2000,
    summary: '東京都世田谷区で一家4人が殺害された未解決事件。多数の遺留品がありDNA型も判明しているが、犯人は25年以上経った現在も不明。',
    tags: '未解決,殺人,家族殺害,東京,歴史的事件',
    views: 4560,
  };

  const setagayaPosts = [
    {
      author: '事件研究家',
      content: '2000年12月30日に発生した世田谷一家殺害事件。発生から25年以上が経過しましたが、いまだに犯人は捕まっていません。遺留品が多数残されているにもかかわらず未解決。韓国製のスニーカー、イタリア製のジャケットなど海外ブランドの遺留品から、外国人犯行説も根強いです。',
      date: '2026-03-15 10:30:00',
    },
    {
      author: '匿名捜査官',
      content: '遺留品の多さが逆に捜査を難しくしている面もあると思います。DNA型が判明しているのに特定できないということは、データベースに登録のない人物ということですよね。最新のDNA捜査技術で進展があることを期待しています。',
      date: '2026-03-15 12:45:00',
    },
    {
      author: '名無しの探偵',
      content: '地理的プロファイリングの観点から、犯人は現場周辺の地理に詳しい人物だった可能性が高いですね。侵入経路の選び方が計画的に見えます。しかし犯行後にアイスを食べるなどの行動は計画性と矛盾するようにも見えます。',
      date: '2026-03-17 08:15:00',
    },
  ];

  const now = '2026-04-01 00:00:00';

  const insertAll = db.transaction(() => {
    // 世田谷事件を先に挿入
    const sgResult = insertCase.run(
      setagayaCase.slug,
      setagayaCase.title,
      setagayaCase.year,
      setagayaCase.summary,
      setagayaCase.tags,
      setagayaCase.views,
      setagayaPosts.length,
      now,
      setagayaPosts.length > 0 ? setagayaPosts[setagayaPosts.length - 1].date : now
    );
    for (const p of setagayaPosts) {
      insertPost.run(sgResult.lastInsertRowid, p.author, p.content, p.date);
    }

    // 全事件を挿入
    for (const c of allCases) {
      const posts = samplePosts[c.slug] || [];
      const result = insertCase.run(
        c.slug,
        c.title,
        c.year,
        c.summary,
        c.tags,
        c.views,
        posts.length,
        now,
        posts.length > 0 ? posts[posts.length - 1].date : now
      );
      for (const p of posts) {
        insertPost.run(result.lastInsertRowid, p.author, p.content, p.date);
      }
    }
  });

  insertAll();
}

module.exports = db;
